/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package firstempgui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author EThornbury
 */
public class EmpGUI extends javax.swing.JFrame {
    ArrayList<Employee> elist;  //declare
    /**
     * Creates new form EmpGUI
     */
    public EmpGUI() {
        initComponents();
        elist = new ArrayList<>(); //create
        //hide items on the form
        hoursLBL.setVisible(false);  //hiding fields
        hoursTF.setVisible(false);
        rateLBL.setVisible(false);
        rateTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empBTNGrp = new javax.swing.ButtonGroup();
        titleLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idLBL = new javax.swing.JLabel();
        hoursLBL = new javax.swing.JLabel();
        rateLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        hoursTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        basicRB = new javax.swing.JRadioButton();
        floorStaffRB = new javax.swing.JRadioButton();
        saveBTN = new javax.swing.JButton();
        loadBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLBL.setText("Employee Dashboard");

        nameLBL.setText("Name: ");

        idLBL.setText("ID: ");

        hoursLBL.setText("Hours:");

        rateLBL.setText("Rate: ");

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        empBTNGrp.add(basicRB);
        basicRB.setText("basic Employee");
        basicRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicRBActionPerformed(evt);
            }
        });

        empBTNGrp.add(floorStaffRB);
        floorStaffRB.setText("floor staff");
        floorStaffRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorStaffRBActionPerformed(evt);
            }
        });

        saveBTN.setText("SAVE to file");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        loadBTN.setText("LOAD from file");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(titleLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayBTN)
                        .addGap(50, 50, 50)
                        .addComponent(saveBTN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLBL)
                                .addGap(82, 82, 82)
                                .addComponent(idTF, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLBL)
                                    .addComponent(hoursLBL)
                                    .addComponent(rateLBL))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(hoursTF)
                                    .addComponent(rateTF)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBTN)
                                .addGap(50, 50, 50)
                                .addComponent(loadBTN)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(basicRB)
                                    .addComponent(floorStaffRB))
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(exitBTN)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLBL)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basicRB))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLBL)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(floorStaffRB)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursLBL)
                    .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLBL)
                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBTN)
                    .addComponent(saveBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(exitBTN)
                    .addComponent(loadBTN))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        //if the basicRB then add those fields to a tempE obj
        
        if(basicRB.isSelected()){
            //need a temp Employee obj
            Employee tempE = new Employee();
            //get the date from the textfields on the JFrame Form
            String name = nameTF.getText();
            tempE.setName(name);
            tempE.setId(idTF.getText());
            //add the temp Employee obj to the arraylist
            elist.add(tempE);
            //reply to user
            displayTA.setText("employee added: " +tempE.getName() + "\n size of elist: " +elist.size()); 
            //clear down text fields
             nameTF.setText("");
            idTF.setText(""); 
        }else if(floorStaffRB.isSelected()){//else the floorStaffRB add those fields to tempFS obj
            FloorStaff tempFS = new FloorStaff();
            tempFS.setName(nameTF.getText());
            tempFS.setId(idTF.getText());
            tempFS.setRate(Double.parseDouble(rateTF.getText()));
            tempFS.setHours(Integer.parseInt(hoursTF.getText()));
            elist.add(tempFS); //add to elist
            displayTA.setText("employee added: " +tempFS.toString() + "\n size of elist: " +elist.size()); 
            //clear fields
             nameTF.setText("");
            idTF.setText(""); 
            hoursTF.setText("");
            rateTF.setText("");
        }

    }//GEN-LAST:event_addBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitBTNActionPerformed

    private void basicRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicRBActionPerformed
        // TODO add your handling code here:
        //show
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        idLBL.setVisible(true);
        idTF.setVisible(true);
        //hide below
        hoursLBL.setVisible(false);
        hoursTF.setVisible(false);
        rateLBL.setVisible(false);
        rateTF.setVisible(false);
        
    }//GEN-LAST:event_basicRBActionPerformed

    private void floorStaffRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorStaffRBActionPerformed
        // TODO add your handling code here:
        //show
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        idLBL.setVisible(true);
        idTF.setVisible(true);
        //show all
        hoursLBL.setVisible(true);
        hoursTF.setVisible(true);
        rateLBL.setVisible(true);
        rateTF.setVisible(true);
    }//GEN-LAST:event_floorStaffRBActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        File f; //file
        FileOutputStream fs; 
        ObjectOutputStream os;
        //try catch
        try{
            f = new File("log.dat");
            fs = new FileOutputStream(f);
            os = new ObjectOutputStream(fs);
            
            os.writeObject(elist);
            os.close();
            displayTA.setText("Employee list written to file");
            //close
        }catch(IOException e){
            System.out.println("Error writing to file: " +e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        File f; //declarations
        FileInputStream fs;
        ObjectInputStream os;
        
        try{
            f = new File("log.dat"); //creates
            fs = new FileInputStream(f);
            os = new ObjectInputStream(fs);
            elist = (ArrayList<Employee>)os.readObject();
            //displayTA.append("read from file, size: " +elist.size()); //test line       
            os.close();
        }catch(IOException e){
            System.out.println("Error reading from file "+e);
        }catch(ClassNotFoundException c){
            System.out.println("Class not found error " +c);
        }
   
    }//GEN-LAST:event_loadBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:

         for(int i = 0; i < elist.size(); i++){
            Employee e = elist.get(i);
            displayTA.append(e.toString()+"\n"); //check the method name for displaying details
         }
        
    }//GEN-LAST:event_displayBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton basicRB;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.ButtonGroup empBTNGrp;
    private javax.swing.JButton exitBTN;
    private javax.swing.JRadioButton floorStaffRB;
    private javax.swing.JLabel hoursLBL;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel rateLBL;
    private javax.swing.JTextField rateTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
