/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee;

import employee.Cleaner;
import employee.Employee;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author EThornbury
 */
public class EmpGUI extends javax.swing.JFrame {

    ArrayList<Employee> elist;  //declare

    /**
     * Creates new form EmpGUI
     */
    public EmpGUI() {
        initComponents();
        elist = new ArrayList<>(); //create
        //hide items on the form
        hoursLBL.setVisible(false);  //hiding fields
        hoursTF.setVisible(false);
        rateLBL.setVisible(false);
        rateTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empBTNGrp = new javax.swing.ButtonGroup();
        titleLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idLBL = new javax.swing.JLabel();
        hoursLBL = new javax.swing.JLabel();
        rateLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        hoursTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        employeeRB = new javax.swing.JRadioButton();
        cleanerRB = new javax.swing.JRadioButton();
        loadBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLBL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titleLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLBL.setText("Employee Dashboard");

        nameLBL.setText("Name: ");

        idLBL.setText("ID: ");

        hoursLBL.setText("Hours:");

        rateLBL.setText("Rate: ");

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        empBTNGrp.add(employeeRB);
        employeeRB.setText("Employee");
        employeeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRBActionPerformed(evt);
            }
        });

        empBTNGrp.add(cleanerRB);
        cleanerRB.setText("Cleaner");
        cleanerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanerRBActionPerformed(evt);
            }
        });

        loadBTN.setText("Load");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLBL)
                                    .addComponent(hoursLBL)
                                    .addComponent(rateLBL)
                                    .addComponent(idLBL))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTF)
                                    .addComponent(hoursTF)
                                    .addComponent(rateTF)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadBTN)
                                .addGap(21, 21, 21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeRB)
                                    .addComponent(cleanerRB))
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(exitBTN)
                                .addGap(55, 55, 55))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(displayBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBTN))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLBL)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLBL)
                    .addComponent(cleanerRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateLBL)
                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBTN)
                    .addComponent(displayBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBTN)
                    .addComponent(loadBTN)
                    .addComponent(addBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        //if the basicRB then add those fields to a tempE obj

        if (employeeRB.isSelected()) {
            //need a temp Employee obj
            Employee tempE = new Employee();
            //get the date from the textfields on the JFrame Form
            String name = nameTF.getText();
            tempE.setName(name);
            tempE.setId(idTF.getText());
            //add the temp Employee obj to the arraylist
            elist.add(tempE);
            //reply to user
            displayTA.setText("employee added: " + tempE.getName() + "\n size of elist: " + elist.size());
            //clear down text fields
            nameTF.setText("");
            idTF.setText("");
        } else if (cleanerRB.isSelected()) {//else the floorStaffRB add those fields to tempFS obj
            Cleaner tempFS = new Cleaner();
            tempFS.setName(nameTF.getText());
            tempFS.setId(idTF.getText());
            tempFS.setHourly(Double.parseDouble(rateTF.getText()));
            tempFS.setHours(Integer.parseInt(hoursTF.getText()));
            elist.add(tempFS); //add to elist
            displayTA.setText("employee added: " + tempFS.toString() + "\n size of elist: " + elist.size());
            //clear fields
            nameTF.setText("");
            idTF.setText("");
            hoursTF.setText("");
            rateTF.setText("");
        }

    }//GEN-LAST:event_addBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitBTNActionPerformed

    private void employeeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRBActionPerformed
        // TODO add your handling code here:
        //show
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        idLBL.setVisible(true);
        idTF.setVisible(true);
        //hide below
        hoursLBL.setVisible(false);
        hoursTF.setVisible(false);
        rateLBL.setVisible(false);
        rateTF.setVisible(false);

    }//GEN-LAST:event_employeeRBActionPerformed

    private void cleanerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanerRBActionPerformed
        // TODO add your handling code here:
        //show
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        idLBL.setVisible(true);
        idTF.setVisible(true);
        //show all
        hoursLBL.setVisible(true);
        hoursTF.setVisible(true);
        rateLBL.setVisible(true);
        rateTF.setVisible(true);
    }//GEN-LAST:event_cleanerRBActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        //load from file

        File f; //declarations
        FileInputStream fs;
        ObjectInputStream os;

        try {
            f = new File("log.dat"); //creates
            fs = new FileInputStream(f);
            os = new ObjectInputStream(fs);
            elist = (ArrayList<Employee>) os.readObject();
            //displayTA.append("read from file, size: " +elist.size()); //test line      
            os.close();
        } catch (IOException e) {
            System.out.println("Error reading from file " + e);
        } catch (ClassNotFoundException c) {
            System.out.println("Class not found error " + c);
        }

    }//GEN-LAST:event_loadBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        File f; //file
        FileOutputStream fs;
        ObjectOutputStream os;
        //try catch
        try {
            f = new File("log.dat");
            fs = new FileOutputStream(f);
            os = new ObjectOutputStream(fs);

            os.writeObject(elist);
            os.close();
            displayTA.setText("Employee list written to file");
            //close
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
//displayBTN code

        for (int i = 0; i < elist.size(); i++) {
            Employee e = elist.get(i);
            displayTA.append(e.getName() + "\n");
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton cleanerRB;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.ButtonGroup empBTNGrp;
    private javax.swing.JRadioButton employeeRB;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel hoursLBL;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBTN;
    private javax.swing.JButton loadBtn;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel rateLBL;
    private javax.swing.JTextField rateTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
